/**
 * MulberrySymbol — renders a bundled Mulberry pictogram.
 *
 *   Source:   https://mulberrysymbols.org  (mulberrysymbols/mulberry-symbols)
 *   Licence:  Creative Commons BY-SA 4.0
 *   Attribution requirement: credit must be shown somewhere in-app
 *     (Profile / About screen).
 *
 * Every glyph is rendered inside a square 1:1 frame with
 *   preserveAspectRatio="xMidYMid meet"
 * so the visual size of the symbol stays uniform across the board —
 * regardless of the original artist's viewBox or the glyph's aspect.
 * The asset map points at normalised SVGs (see scripts/normaliseMulberrySvg.ts)
 * which were trimmed to a tight bbox + uniform inner padding at build time.
 *
 * Production path uses `src/data/mulberryAssetMap.generated.ts`, generated by
 * `scripts/importMulberry.ts`, so every SVG is statically known to Metro and
 * resolves to a local URI through `expo-asset`.
 */

import React, { useEffect, useMemo, useState } from 'react';
import { View } from 'react-native';
import { Asset } from 'expo-asset';
import { SvgUri } from 'react-native-svg';
import { MULBERRY_ASSET_MAP } from '../../data/mulberryAssetMap.generated';

export type MulberrySymbolProps = {
  /** Preferred production lookup: `SymbolItem.id`, e.g. `mulberry_hello_x1y2`. */
  symbolId?: string;
  /** Legacy short-name lookup, e.g. "want", "more", "happy". Resolves through MULBERRY_ASSET_MAP by prefix. */
  name?: string;
  size?: number;
};

// Memoised lookup for the legacy `name` prop. The asset-map keys are
// `mulberry_<slug>_<hash>`, so we strip the trailing hash to find the
// first match for a given name. Built lazily, once.
let nameToIdCache: Map<string, number> | null = null;

function ensureNameIndex(): Map<string, number> {
  if (nameToIdCache) return nameToIdCache;
  const index = new Map<string, number>();
  for (const [key, moduleId] of Object.entries(MULBERRY_ASSET_MAP)) {
    // key = `mulberry_<slug>_<hash>` → slug
    const stripped = key.replace(/^mulberry_/, '').replace(/_[a-z0-9]+$/, '');
    if (!index.has(stripped)) index.set(stripped, moduleId);
  }
  nameToIdCache = index;
  return index;
}

function resolveModuleId(symbolId?: string, name?: string): number | undefined {
  if (symbolId && symbolId in MULBERRY_ASSET_MAP) {
    return MULBERRY_ASSET_MAP[symbolId];
  }
  if (name) {
    const slug = name.toLowerCase().replace(/[\s-]+/g, '_').replace(/[^a-z0-9_]/g, '');
    const index = ensureNameIndex();
    return index.get(slug);
  }
  return undefined;
}

export function MulberrySymbol({ symbolId, name, size = 56 }: MulberrySymbolProps) {
  const [uri, setUri] = useState<string | null>(null);
  const moduleId = useMemo(() => resolveModuleId(symbolId, name), [symbolId, name]);

  useEffect(() => {
    let cancelled = false;
    async function resolveAsset() {
      if (!moduleId) {
        setUri(null);
        return;
      }
      const asset = Asset.fromModule(moduleId);
      await asset.downloadAsync();
      if (!cancelled) setUri(asset.localUri ?? asset.uri);
    }
    resolveAsset();
    return () => {
      cancelled = true;
    };
  }, [moduleId]);

  // Square frame is what guarantees visual uniformity: even if an SVG
  // somehow shipped with a non-square viewBox, the SvgUri will scale to
  // fit the frame, and `preserveAspectRatio="xMidYMid meet"` (baked into
  // every normalised svg, and applied here as a safety belt) keeps the
  // glyph centred without distortion.
  return (
    <View style={{ width: size, height: size, alignItems: 'center', justifyContent: 'center' }}>
      {uri ? (
        <SvgUri
          uri={uri}
          width={size}
          height={size}
          preserveAspectRatio="xMidYMid meet"
        />
      ) : null}
    </View>
  );
}

/** Returns true iff the asset map can resolve this id or short name. */
export function hasMulberrySymbol(idOrName: string): boolean {
  if (idOrName in MULBERRY_ASSET_MAP) return true;
  return resolveModuleId(undefined, idOrName) !== undefined;
}

/** Sorted list of every Mulberry id currently bundled. */
export const MULBERRY_KEYS = Object.keys(MULBERRY_ASSET_MAP).sort();
