/**
 * MulberrySymbol — renders a bundled Mulberry pictogram.
 *
 *   Source:   https://mulberrysymbols.org  (mulberrysymbols/mulberry-symbols)
 *   Licence:  Creative Commons BY-SA 4.0
 *   Attribution requirement: credit must be shown somewhere in-app
 *     (Profile / About screen).
 *
 * Production path uses `src/data/mulberryAssetMap.generated.ts`, generated by
 * `scripts/importMulberry.ts`, so every SVG is statically known to Metro and
 * resolves to a local URI through `expo-asset`.
 */

import React, { useEffect, useState } from 'react';
import { Asset } from 'expo-asset';
import { SvgUri, SvgXml } from 'react-native-svg';
import { MULBERRY_ASSET_MAP } from '../../data/mulberryAssetMap.generated';
import {
  MULBERRY_SVGS,
  MulberryKey,
} from '../../data/mulberrySymbols.generated';

export type MulberrySymbolProps = {
  /** Preferred production lookup: `SymbolItem.id`, e.g. `mulberry_hello_x1y2`. */
  symbolId?: string;
  /** Legacy curated lookup by short key, e.g. "want", "more", "happy". */
  name?: string;
  size?: number;
};

export function MulberrySymbol({ symbolId, name, size = 56 }: MulberrySymbolProps) {
  const [uri, setUri] = useState<string | null>(null);
  const moduleId = symbolId ? MULBERRY_ASSET_MAP[symbolId] : undefined;
  const fallbackXml = name ? MULBERRY_SVGS[name as MulberryKey] : undefined;

  useEffect(() => {
    let cancelled = false;
    async function resolveAsset() {
      if (!moduleId) {
        setUri(null);
        return;
      }
      const asset = Asset.fromModule(moduleId);
      await asset.downloadAsync();
      if (!cancelled) setUri(asset.localUri ?? asset.uri);
    }
    resolveAsset();
    return () => {
      cancelled = true;
    };
  }, [moduleId]);

  if (uri) return <SvgUri uri={uri} width={size} height={size} />;
  if (fallbackXml) return <SvgXml xml={fallbackXml} width={size} height={size} />;
  return null;
}

/** Returns true iff the full bundle or curated fallback ships a glyph. */
export function hasMulberrySymbol(name: string): boolean {
  return name in MULBERRY_ASSET_MAP || name in MULBERRY_SVGS;
}

/** Sorted list of every Mulberry key currently bundled. */
export const MULBERRY_KEYS = Object.keys(MULBERRY_ASSET_MAP).sort();
