import * as SQLite from 'expo-sqlite';
import { defaultDatabaseDirectory, openDatabaseAsync } from 'expo-sqlite';
import * as FileSystem from 'expo-file-system/legacy';
import { Asset } from 'expo-asset';
import {
  SYMBOL_BRAIN_DB_VERSION,
  SYMBOL_BRAIN_MIGRATIONS,
} from './migrations';

export type TapTalkDatabase = SQLite.SQLiteDatabase;

const DB_NAME = 'taptalk_symbol_brain.db';

let bundledDbModule: number | undefined;
try {
  // Generated by `npm run build:symbol-db` — optional until the asset exists.
  bundledDbModule = require('../../../assets/databases/taptalk_symbol_brain.db');
} catch {
  bundledDbModule = undefined;
}
let databasePromise: Promise<TapTalkDatabase> | null = null;
let bundledInstallPromise: Promise<void> | null = null;

async function getUserVersion(db: TapTalkDatabase): Promise<number> {
  const row = await db.getFirstAsync<{ user_version: number }>('PRAGMA user_version');
  return row?.user_version ?? 0;
}

async function setUserVersion(db: TapTalkDatabase, version: number) {
  await db.execAsync(`PRAGMA user_version = ${version};`);
}

async function databaseHasSymbols(db: TapTalkDatabase): Promise<boolean> {
  const row = await db.getFirstAsync<{ count: number }>(
    'SELECT COUNT(*) AS count FROM symbols WHERE source = ?',
    'Mulberry Symbols',
  );
  return (row?.count ?? 0) > 0;
}

async function installBundledDatabaseIfNeeded(): Promise<void> {
  if (!bundledDbModule) return;
  if (bundledInstallPromise) return bundledInstallPromise;

  bundledInstallPromise = (async () => {
    try {
      const destDir = defaultDatabaseDirectory;
      const destPath = `${destDir}/${DB_NAME}`;
      const info = await FileSystem.getInfoAsync(destPath);
      if (info.exists) {
        const probe = await openDatabaseAsync(DB_NAME);
        const populated = await databaseHasSymbols(probe);
        await probe.closeAsync();
        if (populated) return;
        await FileSystem.deleteAsync(destPath, { idempotent: true });
      }

      const asset = Asset.fromModule(bundledDbModule);
      await asset.downloadAsync();
      const sourceUri = asset.localUri ?? asset.uri;
      if (!sourceUri) return;

      await FileSystem.makeDirectoryAsync(destDir, { intermediates: true }).catch(() => {});
      await FileSystem.copyAsync({ from: sourceUri, to: destPath });
    } catch (e) {
      if (__DEV__) console.warn('Bundled symbol DB install skipped:', e);
    }
  })();

  return bundledInstallPromise;
}

export function hasBundledSymbolDatabase(): boolean {
  return bundledDbModule !== undefined;
}

export async function openSymbolBrainDatabase(): Promise<TapTalkDatabase> {
  if (!databasePromise) {
    databasePromise = installBundledDatabaseIfNeeded().then(async () => {
      const db = await openDatabaseAsync(DB_NAME);
      await migrateSymbolBrainDatabase(db);
      return db;
    });
  }
  return databasePromise;
}

export async function migrateSymbolBrainDatabase(db: TapTalkDatabase) {
  const currentVersion = await getUserVersion(db);
  if (currentVersion >= SYMBOL_BRAIN_DB_VERSION) return;

  for (let index = currentVersion; index < SYMBOL_BRAIN_MIGRATIONS.length; index += 1) {
    const migration = SYMBOL_BRAIN_MIGRATIONS[index];
    if (migration) {
      await db.execAsync(migration);
    }
  }
  await setUserVersion(db, SYMBOL_BRAIN_DB_VERSION);
}

export async function resetSymbolBrainDatabaseForDev() {
  if (!__DEV__) return;
  const db = await openSymbolBrainDatabase();
  await db.execAsync(`
    DELETE FROM symbols;
    DELETE FROM concepts;
    DELETE FROM keywords;
    DELETE FROM symbol_tags;
    DELETE FROM user_symbol_preferences;
    DELETE FROM search_history;
    DELETE FROM licence_attribution;
    DELETE FROM derived_symbols;
    DELETE FROM custom_symbols;
  `);
}
